opensearch:
  host: https://172.16.30.210:9200
  username: admin
  password: SUA_SENHA
  verify_ssl: false

polling:
  interval: 10

notifications:
  rules:
    - 553

  critical_paths:
    '\\fs-p3\Financeiro'
  
  recipients:
    - 'karl.richard@getecinformatica.com.br'