apiVersion: batch/v1
kind: CronJob

metadata:
  name: wazuh-notifier
  namespace: wazuh-dev

spec:
  schedule: "0 * * * *"

  concurrencyPolicy: Forbid

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:

      backoffLimit: 2
      ttlSecondsAfterFinished: 300

      template:
        metadata:
          labels:
            app: wazuh-notifier

        spec:

          restartPolicy: Never

          containers:
            - name: wazuh-notifier

              image: ghcr.io/karl-getec/wazuh-notifier:latest

              imagePullPolicy: Always

              env:
                - name: CONFIG_FILE
                  value: /config/app.yaml

              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"

              volumeMounts:
                - name: config
                  mountPath: /config
                  readOnly: true

          volumes:
            - name: config
              configMap:
                name: wazuh-notifier-config