apiVersion: v1
kind: Secret

metadata:
  name: wazuh-notifier-secret
  namespace: wazuh-dev

type: Opaque

stringData:

  OPENSEARCH_HOST: "wazuh-indexer"
  OPENSEARCH_PORT: "9200"

  OPENSEARCH_USERNAME: "admin"
  OPENSEARCH_PASSWORD: "SUA_SENHA"

  OPENSEARCH_VERIFY_CERTS: "false"