opensearch:
  host: wazuh-indexer
  port: 9200
  username: admin
  password: WazuhSecretPassword
  verify_certs: false

polling:
  interval: 30

notifications:
  rules:
    - 553

  critical_paths:
    - "\\\\fs-p3\\Financeiro"

smtp:
  enabled: true

  host: smtp.gmail.com
  port: 587

  username: "karl.richard@getecinformatica.com.br"
  password: "inms sxwh ubnc oroh"

  sender: "alerts@getecinformatica.com.br"
  recipients:
    - karl.richard@getecinformatica.com.br
    - andreluizsalata@gmail.com